language: cpp
dist: bionic
sudo: true
compiler: gcc

addons:
  apt:
    packages:
      - cmake
      - valgrind
      - lcov
      - cppcheck

before_script:
  - mkdir build && cd build
  - cmake ..
  - make

jobs:
  include:
    - stage: tests
      name: "Run tests"
      script:
        - ./tests

    - stage: cppcheck
      name: "Static analisys"
      script:
        - cppcheck --inconclusive --enable=all --language=c ../src/*.c ../src/*.h
        - cppcheck --inconclusive --enable=all --language=c++ ../src/*.cpp

    - stage: coverage
      name: "Test coverage"
      script:
        - ./tests
        - cd CMakeFiles/tests.dir/src
        - gcov tests.cpp.gcno
        - lcov --capture --directory . --output-file test.info
        - genhtml test.info --output-directory ../../../coverage-report
        - cd ../../../

    - stage: memcheck
      name: "Static analysis"
      script:
        - valgrind --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./tests