name: CI

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install requirements
        run: sudo apt-get install build-essential libgtest-dev git cppcheck lcov valgrind
        
      - name: install gtest
        run: cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib && mkdir -p /usr/local/lib/gtest/ && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/gtest/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/gtest/libgtest_main.a

      - name: cppcheck
        run: cppcheck --inconclusive --enable=all --language=c src/*.c src/*.h && cppcheck --inconclusive --enable=all --language=c++ src/*.cpp

      - name: build
        run: mkdir build && cmake -B build . && make -C build

      - name: tests
        run: ./build/tests

      - name: get code coverage
        run: cd build/CMakeFiles/tests.dir/src && gcov *.gcno && lcov --capture --directory . --output-file test.info && mkdir coverage && genhtml test.info --output-directory coverage

      - name: coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: build/CMakeFiles/tests.dir/src/coverage

      - name: valgrind
        run: valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --undef-value-errors=no --verbose ./build/tests
