name: CI

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install compilers
        run: sudo apt install build-essential

      - name: install git
        run: sudo apt install git
        
      - name: install cppcheck
        run: sudo apt install cppcheck

      - name: install lcov
        run: sudo apt install lcov

      - name: install valgrind
        run: sudo apt install valgrind

      - name: cppcheck
        run: cppcheck src/*

      - name: build
        run: mkdir build && cmake -B build . && make -C build

      - name: tests
        run: ./build/tests

      - name: get code coverage
        run: cd build/CMakeFiles/tests.dir/src && gcov *.gcno && lcov --capture --directory . --output-file test.info && mkdir coverage && genhtml test.info --output-directory coverage

      - name: coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: build/CMakeFiles/tests.dir/src/coverage

      - name: valgrind
        run: valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --undef-value-errors=no --verbose ./build/tests
